### ISSUE TITLE
BlendedMVS training code & dataset code

### ISSUE THREAD

**Issue by DingYikang** [yhw-yhw/D2HC-RMVSNet#10]
Hi, 
Thanks for your excellent work. I'm wondering will you release the blended training code & dataset code? I have retrianed this model using BlendedMVS by my implement-code, but the models performance is worse than your pretrained model.
Thanks!

**Comment by weizizhuang** [comment]
Actually we have provided the dataset codes for BlendedMVS in the 'datasets' folder, which are 'dtu_yao_blend.py' (for training) and 'data_eval_transform_blend.py' (for testing) , the only thing for training on this dataset is to change the training scripts (train.sh).  
Note that the given pretrained model is trained on BlendedMVS for 4 epochs.
