### ISSUE TITLE
How do you compute the memory required?

### ISSUE THREAD

**Issue by mazeyu** [yhw-yhw/D2HC-RMVSNet#11]
Hi, since you reported memory usage in the paper and I noticed you have commented some memory usage in the code, so I am wondering if you use some package or the command "nvidia-smi" to report the memory. Thank you!

**Comment by weizizhuang** [comment]
Yes, just by the command 'nvidia-smi'.

**Comment by mazeyu** [comment]
Then, a follow-up question, for all this kind of general memory experiment, just wondering when to call 'nvidia-smi' or repeatedly? (since the memory is always fluctuating due to some caching mechanism.) Thanks!
