### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by mzytmp** [yhw-yhw/D2HC-RMVSNet#13]
Hi, I'm asking about the implementation details. You mentioned in your paper the network for DTU  is trained on 2 GPU with batchsize 6, but in your script train.sh, I don't see this. Also, is the resolution for DTU inference 480 x 640 according to eval_dtu.sh? Maybe it's not mentioned in the paper. Thank you for clarification!

**Comment by weizizhuang** [comment]
In this version we apply 4 GPU with batchsize 4 for training. Actually, benefited from the Group Normalization (GN), our network is not very sensitive to the batchsize.
For any question about the setting of parameters, please refer to our released codebase.

**Comment by mazeyu** [comment]
Thanks for clarification! (that is my another acoount)
