### ISSUE TITLE
about fusion.py

### ISSUE THREAD

**Issue by JANEKKO** [yhw-yhw/D2HC-RMVSNet#15]
hello , thanks for share. i wonder the dynamic consistency checking noted in the paper is not the same with the code in fusion.py. maybe i did not get it ,could you give some guidance?

**Comment by doubleZ0108** [comment]
I think I also have this problem.
I just wonder if `fusion.py` is the one used in the paper?

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。

**Comment by BobrG** [comment]
I don't get where can I find a part with exponent from the paper which was used to quantify the depth matching consistency. Can you give clarification pls?

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。
