### ISSUE TITLE
Which datasets is your pretrained model trained on, DTU or BlendedMVS?

### ISSUE THREAD

**Issue by fanhuanhuan** [yhw-yhw/D2HC-RMVSNet#2]
Hi, Which datasets is your pretrained model trained on, DTU or BlendedMVS?

**Comment by yhw-yhw** [comment]
We only trained our model on the DTU dataset, and directly test on the other datasets, as described in our paper.

**Comment by fanhuanhuan** [comment]
Thanks for your answer, I hava tested the model on my own dataset, the result is great. Have you trained on the BlendedMVS, and what have the results been?

**Comment by yhw-yhw** [comment]
We are planning to train our network on the BlendedMVS, if we have finished it, we will keep you noticed.

**Comment by fanhuanhuan** [comment]
OK, thank you
