### ISSUE TITLE
To confirm I have run your code with the best performance

### ISSUE THREAD

**Issue by mazeyu** [yhw-yhw/D2HC-RMVSNet#9]
Hi, since I am working on a similar project and would like to use D2HC-RMVSNet as a reference. So, currently I have run it on Tanks and Temples training set and got the following results, which is very good:

f1 score | Barn | Caterpillar | Church | Courthouse | Ignatius | Meetingroom | Truck | mean
D2HC RMVSNet | 0.6555 | 0.6104 | 0.5421 | 0.594 | 0.8193 | 0.4095 | 0.7392 | 0.62428571

So I just want to make sure it is consistent with your best performance on that data (if you have these results)
(although I think I have followed your code exactly and it should be consistent)
Thank you!!

**Comment by QT-Zhu** [comment]
Yes. We once tested the algorithm casually (with some randomly picked model) and the results are not as good as yours. So I think you have already achieved the best performance.

**Comment by mazeyu** [comment]
Thanks!

**Comment by zhz120** [comment]
can you tell me how to set the parameter in  blendedmvs,train and test,thanks

> Hi, since I am working on a similar project and would like to use D2HC-RMVSNet as a reference. So, currently I have run it on Tanks and Temples training set and got the following results, which is very good:
> 
> f1 score | Barn | Caterpillar | Church | Courthouse | Ignatius | Meetingroom | Truck | mean D2HC RMVSNet | 0.6555 | 0.6104 | 0.5421 | 0.594 | 0.8193 | 0.4095 | 0.7392 | 0.62428571
> 
> So I just want to make sure it is consistent with your best performance on that data (if you have these results) (although I think I have followed your code exactly and it should be consistent) Thank you!!

can you tell me how to set the parameter in blended , train and test, thanks

**Comment by mazeyu** [comment]
I only tested on T&T using the provided .sh
